-- AlterTable
ALTER TABLE `users` ADD COLUMN `feature_overrides` JSON NULL,
    MODIFY `status` ENUM('PENDING_VERIFICATION', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'PENDING_VERIFICATION';
