<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;

class PackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            [
                'name' => 'Starter Website',
                'slug' => 'starter-website',
                'short_description' => 'Perfect for individuals and freelancers starting online.',
                'description' => 'A professional starter website with up to 5 pages, modern responsive design, and basic SEO setup. Ideal for personal portfolios, freelancers, and small businesses.',
                'price' => 299.00,
                'currency' => 'USD',
                'delivery_days' => 7,
                'revisions' => 2,
                'features' => [
                    'Up to 5 pages',
                    'Mobile responsive design',
                    'Contact form',
                    'Basic on-page SEO',
                    'Google Maps integration',
                    'Social media links',
                    'Fast loading (optimized)',
                    '1 month free support',
                ],
                'is_featured' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'Business Website',
                'slug' => 'business-website',
                'short_description' => 'Professional website for established businesses.',
                'description' => 'A comprehensive business website with up to 10 pages, premium design, CMS, and all the features your business needs to grow online.',
                'price' => 599.00,
                'currency' => 'USD',
                'delivery_days' => 14,
                'revisions' => 3,
                'features' => [
                    'Up to 10 pages',
                    'Premium custom design',
                    'CMS (content management)',
                    'Blog setup',
                    'Advanced on-page SEO',
                    'Contact form & lead capture',
                    'Google Analytics integration',
                    'Google Search Console setup',
                    'Speed optimization',
                    'SSL certificate help',
                    '3 months free support',
                ],
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Premium Website',
                'slug' => 'premium-website',
                'short_description' => 'High-end website with advanced features and animations.',
                'description' => 'A premium, fully custom website with advanced animations, interactive elements, and everything needed to make a lasting impression.',
                'price' => 999.00,
                'currency' => 'USD',
                'delivery_days' => 21,
                'revisions' => 5,
                'features' => [
                    'Unlimited pages',
                    'Custom premium design + animations',
                    'Advanced CMS',
                    'Blog + Portfolio',
                    'Full SEO optimization',
                    'Live chat integration',
                    'Email marketing setup',
                    'Google Analytics + Search Console',
                    'Meta Pixel setup',
                    'Speed + performance optimization',
                    'Security hardening',
                    '6 months free support',
                ],
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'E-Commerce Website',
                'slug' => 'ecommerce-website',
                'short_description' => 'Full-featured online store ready to sell.',
                'description' => 'A complete e-commerce solution with product management, payment gateway, and everything you need to sell online professionally.',
                'price' => 1299.00,
                'currency' => 'USD',
                'delivery_days' => 28,
                'revisions' => 5,
                'features' => [
                    'Full e-commerce setup',
                    'Product catalog management',
                    'Shopping cart + checkout',
                    'Payment gateway integration',
                    'Order management system',
                    'Inventory management',
                    'Mobile-optimized shopping',
                    'SEO for products',
                    'Google Shopping setup',
                    'Speed optimization',
                    '6 months free support',
                ],
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'name' => 'SEO Starter',
                'slug' => 'seo-starter',
                'short_description' => 'Get found on Google with our foundational SEO package.',
                'description' => 'A one-time SEO setup package to optimize your website for search engines, improve rankings, and drive organic traffic.',
                'price' => 249.00,
                'currency' => 'USD',
                'delivery_days' => 7,
                'revisions' => 2,
                'features' => [
                    'Complete SEO audit',
                    'Keyword research (20 keywords)',
                    'On-page optimization (10 pages)',
                    'Meta titles & descriptions',
                    'Google Search Console setup',
                    'Google Analytics setup',
                    'Sitemap submission',
                    'robots.txt optimization',
                    'Page speed audit',
                ],
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Monthly SEO Growth',
                'slug' => 'monthly-seo-growth',
                'short_description' => 'Ongoing SEO management to grow your rankings month by month.',
                'description' => 'A comprehensive monthly SEO management package that continuously improves your rankings, builds authority, and drives consistent organic traffic.',
                'price' => 399.00,
                'currency' => 'USD',
                'delivery_days' => 30,
                'revisions' => -1,
                'features' => [
                    'Monthly keyword tracking',
                    'Content optimization',
                    '4 SEO blog posts/month',
                    'Technical SEO fixes',
                    'Local SEO optimization',
                    'Backlink building',
                    'Monthly performance report',
                    'Google Business Profile management',
                    'Competitor analysis',
                ],
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'name' => 'Digital Marketing',
                'slug' => 'digital-marketing',
                'short_description' => 'Complete digital marketing to grow your brand online.',
                'description' => 'A full digital marketing package including social media management, content creation, paid ads strategy, and brand growth.',
                'price' => 699.00,
                'currency' => 'USD',
                'delivery_days' => 30,
                'revisions' => -1,
                'features' => [
                    'Social media strategy',
                    '12 social media posts/month',
                    'Facebook & Instagram management',
                    'Ad campaign setup & management',
                    'Email marketing campaign',
                    'Monthly analytics report',
                    'Audience growth strategy',
                    'Content calendar',
                ],
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Branding Package',
                'slug' => 'branding-package',
                'short_description' => 'Professional brand identity from logo to full brand guide.',
                'description' => 'Complete brand identity design including logo, color palette, typography, and all the brand assets you need.',
                'price' => 499.00,
                'currency' => 'USD',
                'delivery_days' => 10,
                'revisions' => 4,
                'features' => [
                    'Professional logo design (3 concepts)',
                    'Color palette selection',
                    'Typography system',
                    'Brand style guide (PDF)',
                    'Business card design',
                    'Social media profile kit',
                    'Email signature design',
                    'High-res files (AI, SVG, PNG)',
                ],
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'Website Maintenance',
                'slug' => 'website-maintenance',
                'short_description' => 'Monthly maintenance to keep your website running perfectly.',
                'description' => 'Regular monthly website maintenance including updates, backups, security monitoring, and performance optimization.',
                'price' => 149.00,
                'currency' => 'USD',
                'delivery_days' => 30,
                'revisions' => -1,
                'features' => [
                    'Monthly plugin/theme updates',
                    'Daily backups',
                    'Security monitoring',
                    'Uptime monitoring',
                    'Monthly performance report',
                    'Minor content updates (2 hrs)',
                    'Bug fixes',
                    'SSL certificate renewal',
                ],
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Custom Quote',
                'slug' => 'custom-quote',
                'short_description' => 'Need something unique? Let\'s discuss your specific needs.',
                'description' => 'Have a project that doesn\'t fit into a standard package? Submit a custom quote request and we\'ll design the perfect solution for you.',
                'price' => 0.00,
                'currency' => 'USD',
                'delivery_days' => 1,
                'revisions' => -1,
                'features' => [
                    'Custom scope and timeline',
                    'Tailored to your exact needs',
                    'Flexible pricing',
                    'Dedicated project management',
                    'Priority support',
                ],
                'is_featured' => false,
                'sort_order' => 10,
            ],
        ];

        foreach ($packages as $packageData) {
            Package::firstOrCreate(['slug' => $packageData['slug']], $packageData);
        }
    }
}
